# Generated by Django 3.0.8 on 2020-07-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200716_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='latidude',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Phone', 'Phone'), ('Email', 'Email')], max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
